# Generated by Django 5.0.2 on 2024-03-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_prodcut_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qtu',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='contry',
            new_name='country',
        ),
    ]
